### ISSUE TITLE
Parsing body (form post) without data throws error - PHP 7.4

### ISSUE THREAD

**Issue by rjgamer** [slimphp/Slim-Psr7#162]
You can reproduce the error, by enabling the BodyParsingMiddleware and submit a post form without named input fields.

I used Slim 4, all latest packages and PHP 7.4.

Error message
> Details
> Type: ErrorException
> Code: 0
> Message: Trying to access array offset on value of type bool
> File: \path\to\project\vendor\slim\psr7\src\Stream.php
> Line: 351
> Trace
> 
> #0 C:\dev\Projekte\Tasky\vendor\slim\psr7\src\Stream.php(351): {closure}(8, 'Trying to acces...', '\path\to\project...', 351, Array)
> #1 C:\dev\Projekte\Tasky\vendor\slim\psr7\src\Stream.php(256): Slim\Psr7\Stream->isPipe()
> #2 C:\dev\Projekte\Tasky\vendor\slim\psr7\src\Stream.php(278): Slim\Psr7\Stream->isSeekable()
> #3 C:\dev\Projekte\Tasky\vendor\slim\psr7\src\Stream.php(141): Slim\Psr7\Stream->rewind()
> #4 C:\dev\Projekte\Tasky\vendor\slim\slim\Slim\Middleware\BodyParsingMiddleware.php(161): Slim\Psr7\Stream->__toString()
> #5 C:\dev\Projekte\Tasky\vendor\slim\slim\Slim\Middleware\BodyParsingMiddleware.php(62): Slim\Middleware\BodyParsingMiddleware->parseBody(Object(Slim\Psr7\Request))
> #6 C:\dev\Projekte\Tasky\vendor\slim\slim\Slim\MiddlewareDispatcher.php(140): Slim\Middleware\BodyParsingMiddleware->process(Object(Slim\Psr7\Request), Object(class@anonymous))
> #7 C:\dev\Projekte\Tasky\vendor\slim\slim\Slim\Middleware\RoutingMiddleware.php(60): class@anonymous->handle(Object(Slim\Psr7\Request))
> #8 C:\dev\Projekte\Tasky\vendor\slim\slim\Slim\MiddlewareDispatcher.php(140): Slim\Middleware\RoutingMiddleware->process(Object(Slim\Psr7\Request), Object(class@anonymous))
> #9 C:\dev\Projekte\Tasky\vendor\slim\slim\Slim\Middleware\ErrorMiddleware.php(107): class@anonymous->handle(Object(Slim\Psr7\Request))
> #10 C:\dev\Projekte\Tasky\vendor\slim\slim\Slim\MiddlewareDispatcher.php(140): Slim\Middleware\ErrorMiddleware->process(Object(Slim\Psr7\Request), Object(class@anonymous))
> #11 C:\dev\Projekte\Tasky\vendor\slim\slim\Slim\MiddlewareDispatcher.php(81): class@anonymous->handle(Object(Slim\Psr7\Request))
> #12 C:\dev\Projekte\Tasky\vendor\slim\slim\Slim\App.php(215): Slim\MiddlewareDispatcher->handle(Object(Slim\Psr7\Request))
> #13 C:\dev\Projekte\Tasky\vendor\slim\slim\Slim\App.php(199): Slim\App->handle(Object(Slim\Psr7\Request))
> #14 C:\dev\Projekte\Tasky\public\index.php(86): Slim\App->run(Object(Slim\Psr7\Request))
> #15 {main}

**Comment by rjgamer** [comment]
Additional information about the error message: My app catched the PHP error and throwed an ErrorException.

Used PHP code:
```php
// Throw exception when error occurs
set_error_handler(function ($severity, $message, $file, $line) {
    if (error_reporting() & $severity) {
        throw new ErrorException($message, 0, $severity, $file, $line);
    }
});
```

**Comment by rjgamer** [comment]
Big sorry, my fault. 😢  Slim/Psr7 was not the latest version.
